apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: {{ .Values.version | default .Chart.AppVersion }}
  name: kube-state-metrics
  namespace: {{ template "kube-state-metrics.namespace" . }}
