{{- if and .Values.alertmanager.enabled .Values.alertmanager.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: {{ .Values.alertmanager.version | default .Values.alertmanager.alertmanagerSpec.image.tag }}
  name: alertmanager-main
  namespace: {{ template "kube-prometheus.namespace" . }}
spec:
  {{- if .Values.alertmanager.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.alertmanager.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.alertmanager.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.alertmanager.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: alert-router
      app.kubernetes.io/instance: main
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/part-of: kube-prometheus
{{- end }}
