apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: {{ .Values.version | default .Chart.AppVersion }}
  name: node-exporter
  namespace: {{ template "prometheus-node-exporter.namespace" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: https
    {{- if ( and (eq .Values.service.type "NodePort" ) (not (empty .Values.service.nodePort)) ) }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    port: 9100
    targetPort: https
    protocol: TCP
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: kube-prometheus
