{{- if .Values.prometheus.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: {{ .Values.prometheus.version | default .Values.prometheus.prometheusSpec.image.tag }}
  name: prometheus-k8s
  namespace: {{ template "kube-prometheus.namespace" . }}
spec:
  minAvailable: {{ .Values.prometheus.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
{{- end }}
